# Usa la imagen oficial de PostgreSQL
FROM postgres:latest

# Establece las variables de entorno para la base de datos
ENV POSTGRES_DB=matanza
ENV POSTGRES_USER=matanza
ENV POSTGRES_PASSWORD=juHD121**

# Expon el puerto de PostgreSQL
EXPOSE 5432
