# Generated by Django 5.0.7 on 2024-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quepinta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='entradas_promocion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_entrada',
            field=models.CharField(max_length=100),
        ),
    ]
