# Generated by Django 5.0.7 on 2024-10-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quepinta', '0002_alter_evento_entradas_promocion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='promocion',
        ),
    ]
