# Generated by Django 2.2.12 on 2024-10-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quepinta', '0003_remove_evento_promocion'),
        ('quepinta', '0002_auto_20241023_0359'),
    ]

    operations = [
    ]
