# Generated by Django 4.2.16 on 2024-11-26 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quepinta', '0005_remove_reserva_entrada_reserva_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
