# Generated by Django 5.0.7 on 2024-10-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('cantidad_entradas_disponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duenio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('purchase_parking_pass', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('edad', models.IntegerField()),
                ('localidad', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_entrada', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('hora', models.TimeField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento')),
                ('tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.tipoentrada')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.organizacion'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('no_reserva', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.entrada')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.estado')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventos.promocion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.usuario')),
            ],
        ),
    ]
